server:
  port:80
  tomcat:
  uri-encoding:UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hihernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
